import Head from "next/head";
import { useQuery, Query } from "urql";
import { PRODUCT_QUERY } from "../lib/query";

import { Container, Text } from "@chakra-ui/react";

export default function Home() {
  //Fetch products from strapi

  const [result, reexecuteQuery] = useQuery({
    query: PRODUCT_QUERY,
  });

  const { data, fetching, error } = result;

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  return (
    <div>
      <Head>
        <title>Ecommerce App</title>
        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Container maxW='6xl'>
        <main>
          <Text color='brand.700' fontSize='5xl'>
            Main Page
          </Text>
        </main>
        {console.log(data.inventories.data)}
      </Container>
    </div>
  );
}
